Added Settings
anthonymesa/liquorish-frontend pull request #25
Opened 2022-02-21 07:23 UTC by ketchupmann

2022-02-22 01:03 UTC, anthonymesa requested changes
From now on, no more copying files from other pages to try to retrofit into something new. for every new page you should be starting with a new fresh empty file. Not only will this keep you from having random code in your files that doesn't fit/make sense, but it will also force you to actually learn how the pages are built in React.

Make sure that you go through the documentation to get examples and understanding of how react works: https://reactjs.org/docs/hello-world.html 

Before you continue to make any changes or fixes on this branch, always make sure you run
```
git pull origin main
```
to get the most recent changes from main that you may not have.

Make your changes, then push to this same branch. This pull request is linked to this branch, so when you make a new commit, leave a comment on the pull request letting me know you updated the branch.

2022-03-30 03:21 UTC, ketchupmann commented on src/settings/Settings.js
> +}
fixed

2022-03-30 03:21 UTC, ketchupmann commented on src/settings/Settings.js
> +}
fixed

2022-03-30 03:21 UTC, ketchupmann commented on src/settings/Settings.js
> +}
fixed

2022-03-30 03:22 UTC, ketchupmann commented on src/settings/Settings.js
> +}
fixed

2022-03-30 03:22 UTC, ketchupmann commented on src/settings/Settings.js
> +        </div>
fixed

2022-03-30 03:22 UTC, ketchupmann commented on src/settings/Settings.js
> +// end of additions for Settings A3
fixed

2022-03-30 03:22 UTC, ketchupmann commented on src/settings/Settings.js
> +  }
fixed

2022-03-30 03:22 UTC, ketchupmann commented on src/settings/Settings.js
> +  const [inputconfirmnewpassword, Setinputconfirmnewpassword] = React.useState("");
fixed

2022-03-30 03:22 UTC, ketchupmann commented on src/settings/Settings.js
> +    </div>
fixed

2022-03-30 03:22 UTC, ketchupmann commented on src/settings/Settings.js
> +                    <button className="btnPrimary" onClick={ handleCityState }>Search</button>
fixed

2022-03-30 03:22 UTC, ketchupmann commented on src/settings/Settings.css
> +/* #endregion */
fixed

2022-03-30 03:23 UTC, ketchupmann commented on src/settings/Settings.js
> +            <button className="btnSecondary" onClick={ logoutUser }>Log Out</button>
fixed

2022-03-30 03:23 UTC, ketchupmann commented on src/settings/Settings.js
> +          <button className="btnPrimary" onClick={ handleReset }>Reset</button>
fixed

2022-03-30 07:06 UTC, anthonymesa approved these changes

2022-03-30 07:07 UTC, merged